<?php

namespace Modules\Location\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Location\Http\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $id = 1;
        $state = 1;
        $data = [
            ["id" => $id++, "name" => "Syedpur", "state_id" => 1, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Domar", "state_id" => 1, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dimla", "state_id" => 1, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jaldhaka", "state_id" => 1, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kishorganj", "state_id" => 1, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nilphamari Sadar", "state_id" => 1, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],

            ["id" => $id++, "name" => "Nawabganj", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Birganj", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ghoraghat", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Birampur", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Parbatipur", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bochaganj", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kaharol", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Fulbari", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dinajpur Sadar", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Hakimpur", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Khansama", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Birol", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chirirbandar", "state_id" => 2, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],

            ["id" => $id++, "name" => "Brahmanbaria Sadar", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kasba", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nasirnagar", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sarail", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ashuganj", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Akhaura", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nabinagar", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bancharampur", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bijoynagar", "state_id" => 3, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rangamati Sadar", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kaptai", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kawkhali", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Baghaichari", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Barkal", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Langadu", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rajasthali", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Belaichari", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Juraichari", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Naniarchar", "state_id" => 4, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Noakhali Sadar", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Companiganj", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Begumganj", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Hatia", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Subarnachar", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kabirhat", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Senbug", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chatkhil", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sonaimori", "state_id" => 5, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Haimchar", "state_id" => 6, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kachua", "state_id" => 6, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shahrasti", "state_id" => 6, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chandpur Sadar", "state_id" => 6, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Matlab South", "state_id" => 6, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Hajiganj", "state_id" => 6, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Matlab North", "state_id" => 6, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Faridgonj", "state_id" => 6, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lakshmipur Sadar", "state_id" => 7, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kamalnagar", "state_id" => 7, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Raipur", "state_id" => 7, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ramgati", "state_id" => 7, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ramganj", "state_id" => 7, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rangunia", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sitakunda", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mirsharai", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Patiya", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sandwip", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Banshkhali", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Boalkhali", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Anwara", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chandanaish", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Satkania", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lohagara", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Hathazari", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Fatikchhari", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Raozan", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Karnafuli", "state_id" => 8, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Coxsbazar Sadar", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chakaria", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kutubdia", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ukhiya", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Moheshkhali", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pekua", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ramu", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Teknaf", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Khagrachhari Sadar", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dighinala", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Panchari", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Laxmichhari", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mohalchari", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Manikchari", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ramgarh", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Matiranga", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Guimara", "state_id" => 10, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bandarban Sadar", "state_id" => 11, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Alikadam", "state_id" => 11, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Naikhongchhari", "state_id" => 11, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rowangchhari", "state_id" => 11, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lama", "state_id" => 11, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ruma", "state_id" => 11, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Thanchi", "state_id" => 11, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Belkuchi", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chauhali", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kamarkhand", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kazipur", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Raigonj", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shahjadpur", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sirajganj Sadar", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tarash", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ullapara", "state_id" => 12, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sujanagar", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ishurdi", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhangura", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pabna Sadar", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bera", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Atghoria", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chatmohar", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Santhia", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Faridpur", "state_id" => 13, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kahaloo", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bogra Sadar", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shariakandi", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shajahanpur", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dupchanchia", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Adamdighi", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nondigram", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sonatala", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dhunot", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gabtali", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sherpur", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shibganj", "state_id" => 14, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Paba", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Durgapur", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mohonpur", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Charghat", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Puthia", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bagha", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Godagari", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tanore", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bagmara", "state_id" => 15, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Natore Sadar", "state_id" => 16, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Singra", "state_id" => 16, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Baraigram", "state_id" => 16, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bagatipara", "state_id" => 16, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lalpur", "state_id" => 16, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gurudaspur", "state_id" => 16, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Naldanga", "state_id" => 16, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Akkelpur", "state_id" => 17, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kalai", "state_id" => 17, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Khetlal", "state_id" => 17, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Panchbibi", "state_id" => 17, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Joypurhat Sadar", "state_id" => 17, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chapainawabganj Sadar", "state_id" => 18, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gomostapur", "state_id" => 18, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nachol", "state_id" => 18, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bholahat", "state_id" => 18, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shibganj", "state_id" => 18, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mohadevpur", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Badalgachi", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Patnitala", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dhamoirhat", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Niamatpur", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Manda", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Atrai", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Raninagar", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Naogaon Sadar", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Porsha", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sapahar", "state_id" => 19, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Manirampur", "state_id" => 20, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Abhaynagar", "state_id" => 20, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bagherpara", "state_id" => 20, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chougachha", "state_id" => 20, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jhikargacha", "state_id" => 20, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Keshabpur", "state_id" => 20, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jessore Sadar", "state_id" => 20, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sharsha", "state_id" => 20, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Assasuni", "state_id" => 21, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Debhata", "state_id" => 21, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kalaroa", "state_id" => 21, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Satkhira Sadar", "state_id" => 21, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shyamnagar", "state_id" => 21, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tala", "state_id" => 21, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kaliganj", "state_id" => 21, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mujibnagar", "state_id" => 22, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Meherpur Sadar", "state_id" => 22, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gangni", "state_id" => 22, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Narail Sadar", "state_id" => 23, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lohagara", "state_id" => 23, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kalia", "state_id" => 23, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chuadanga Sadar", "state_id" => 24, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Alamdanga", "state_id" => 24, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Damurhuda", "state_id" => 24, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jibannagar", "state_id" => 24, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kushtia Sadar", "state_id" => 25, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kumarkhali", "state_id" => 25, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Khoksa", "state_id" => 25, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mirpur", "state_id" => 25, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Daulatpur", "state_id" => 25, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bheramara", "state_id" => 25, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shalikha", "state_id" => 26, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sreepur", "state_id" => 26, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Magura Sadar", "state_id" => 26, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mohammadpur", "state_id" => 26, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Paikgasa", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Fultola", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Digholia", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rupsha", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Terokhada", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dumuria", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Botiaghata", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dakop", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Koyra", "state_id" => 27, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Fakirhat", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bagerhat Sadar", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mollahat", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sarankhola", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rampal", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Morrelganj", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kachua", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mongla", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chitalmari", "state_id" => 28, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jhenaidah Sadar", "state_id" => 29, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shailkupa", "state_id" => 29, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Harinakundu", "state_id" => 29, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kaliganj", "state_id" => 29, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kotchandpur", "state_id" => 29, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Moheshpur", "state_id" => 29, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jhalakathi Sadar", "state_id" => 30, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kathalia", "state_id" => 30, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nalchity", "state_id" => 30, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rajapur", "state_id" => 30, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bauphal", "state_id" => 31, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Patuakhali Sadar", "state_id" => 31, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dumki", "state_id" => 31, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dashmina", "state_id" => 31, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kalapara", "state_id" => 31, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mirzaganj", "state_id" => 31, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Galachipa", "state_id" => 31, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rangabali", "state_id" => 31, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pirojpur Sadar", "state_id" => 32, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nazirpur", "state_id" => 32, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kawkhali", "state_id" => 32, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Zianagar", "state_id" => 32, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhandaria", "state_id" => 32, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mathbaria", "state_id" => 32, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nesarabad", "state_id" => 32, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Barisal Sadar", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bakerganj", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Babuganj", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Wazirpur", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Banaripara", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gournadi", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Agailjhara", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mehendiganj", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Muladi", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Hizla", "state_id" => 33, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhola Sadar", "state_id" => 34, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Borhan Sddin", "state_id" => 34, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Charfesson", "state_id" => 34, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Doulatkhan", "state_id" => 34, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Monpura", "state_id" => 34, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tazumuddin", "state_id" => 34, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lalmohan", "state_id" => 34, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Amtali", "state_id" => 35, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Barguna Sadar", "state_id" => 35, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Betagi", "state_id" => 35, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bamna", "state_id" => 35, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pathorghata", "state_id" => 35, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Taltali", "state_id" => 35, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Balaganj", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Beanibazar", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bishwanath", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Companiganj", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Fenchuganj", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Golapganj", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gowainghat", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jaintiapur", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kanaighat", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sylhet Sadar", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Zakiganj", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dakshinsurma", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Osmaninagar", "state_id" => 36, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Barlekha", "state_id" => 37, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kamolganj", "state_id" => 37, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kulaura", "state_id" => 37, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Moulvibazar Sadar", "state_id" => 37, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rajnagar", "state_id" => 37, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sreemangal", "state_id" => 37, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Juri", "state_id" => 37, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nabiganj", "state_id" => 38, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bahubal", "state_id" => 38, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ajmiriganj", "state_id" => 38, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Baniachong", "state_id" => 38, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lakhai", "state_id" => 38, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chunarughat", "state_id" => 38, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Habiganj Sadar", "state_id" => 38, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Madhabpur", "state_id" => 38, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sunamganj Sadar", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "South Sunamganj", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bishwambarpur", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chhatak", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jagannathpur", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dowarabazar", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tahirpur", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dharmapasha", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jamalganj", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shalla", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Derai", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Belabo", "state_id" => 40, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Monohardi", "state_id" => 40, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Narsingdi Sadar", "state_id" => 40, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Palash", "state_id" => 40, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Raipura", "state_id" => 40, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shibpur", "state_id" => 40, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kaliganj", "state_id" => 41, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kaliakair", "state_id" => 41, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kapasia", "state_id" => 41, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gazipur Sadar", "state_id" => 41, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sreepur", "state_id" => 41, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shariatpur Sadar", "state_id" => 42, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Naria", "state_id" => 42, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Zajira", "state_id" => 42, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gosairhat", "state_id" => 42, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhedarganj", "state_id" => 42, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Damudya", "state_id" => 42, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Araihazar", "state_id" => 43, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bandar", "state_id" => 43, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Narayanganj Sadar", "state_id" => 43, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rupganj", "state_id" => 43, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sonargaon", "state_id" => 43, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Basail", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhuapur", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Delduar", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ghatail", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gopalpur", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Madhupur", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mirzapur", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nagarpur", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sakhipur", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tangail Sadar", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kalihati", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dhanbari", "state_id" => 44, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Itna", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Katiadi", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhairab", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tarail", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Hossainpur", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pakundia", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kuliarchar", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kishoreganj Sadar", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Karimgonj", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bajitpur", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Austagram", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mithamoin", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nikli", "state_id" => 45, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Harirampur", "state_id" => 46, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Saturia", "state_id" => 46, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Manikganj Sadar", "state_id" => 46, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gior", "state_id" => 46, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shibaloy", "state_id" => 46, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Doulatpur", "state_id" => 46, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Singiar", "state_id" => 46, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Savar", "state_id" => 47, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dhamrai", "state_id" => 47, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Keraniganj", "state_id" => 47, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nawabganj", "state_id" => 47, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dohar", "state_id" => 47, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Munshiganj Sadar", "state_id" => 48, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sreenagar", "state_id" => 48, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sirajdikhan", "state_id" => 48, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Louhajanj", "state_id" => 48, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gajaria", "state_id" => 48, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tongibari", "state_id" => 48, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rajbari Sadar", "state_id" => 49, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Goalanda", "state_id" => 49, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pangsa", "state_id" => 49, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Baliakandi", "state_id" => 49, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kalukhali", "state_id" => 49, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Madaripur Sadar", "state_id" => 50, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Shibchar", "state_id" => 50, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kalkini", "state_id" => 50, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rajoir", "state_id" => 50, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gopalganj Sadar", "state_id" => 51, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kashiani", "state_id" => 51, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tungipara", "state_id" => 51, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kotalipara", "state_id" => 51, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Muksudpur", "state_id" => 51, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Faridpur Sadar", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Alfadanga", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Boalmari", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sadarpur", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nagarkanda", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhanga", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Charbhadrasan", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Madhukhali", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Saltha", "state_id" => 52, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Panchagarh Sadar", "state_id" => 53, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Debiganj", "state_id" => 53, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Boda", "state_id" => 53, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Atwari", "state_id" => 53, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tetulia", "state_id" => 53, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chhagalnaiya", "state_id" => 54, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Feni Sadar", "state_id" => 54, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sonagazi", "state_id" => 54, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Fulgazi", "state_id" => 54, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Parshuram", "state_id" => 54, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Daganbhuiyan", "state_id" => 54, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lalmonirhat Sadar", "state_id" => 55, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kaliganj", "state_id" => 55, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Hatibandha", "state_id" => 55, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Patgram", "state_id" => 55, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Aditmari", "state_id" => 55, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Debidwar", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Barura", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Brahmanpara", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chandina", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chauddagram", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Daudkandi", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Homna", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Laksam", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Muradnagar", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nangalkot", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Comilla Sadar", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Meghna", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Monohargonj", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sadarsouth", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Titas", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Burichang", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Lalmai", "state_id" => 56, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sadullapur", "state_id" => 57, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gaibandha Sadar", "state_id" => 57, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Palashbari", "state_id" => 57, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Saghata", "state_id" => 57, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gobindaganj", "state_id" => 57, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sundarganj", "state_id" => 57, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Phulchari", "state_id" => 57, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Thakurgaon Sadar", "state_id" => 58, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pirganj", "state_id" => 58, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ranisankail", "state_id" => 58, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Haripur", "state_id" => 58, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Baliadangi", "state_id" => 58, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rangpur Sadar", "state_id" => 59, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gangachara", "state_id" => 59, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Taragonj", "state_id" => 59, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Badargonj", "state_id" => 59, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mithapukur", "state_id" => 59, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pirgonj", "state_id" => 59, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kaunia", "state_id" => 59, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Pirgacha", "state_id" => 59, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kurigram Sadar", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nageshwari", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhurungamari", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Phulbari", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rajarhat", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Ulipur", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Chilmari", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Rowmari", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Charrajibpur", "state_id" => 60, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sherpur Sadar", "state_id" => 61, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nalitabari", "state_id" => 61, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sreebordi", "state_id" => 61, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nokla", "state_id" => 61, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jhenaigati", "state_id" => 61, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Fulbaria", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Trishal", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bhaluka", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Muktagacha", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mymensingh Sadar", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dhobaura", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Phulpur", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Haluaghat", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gouripur", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Gafargaon", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Iswarganj", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Nandail", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Tarakanda", "state_id" => 62, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Jamalpur Sadar", "state_id" => 63, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Melandah", "state_id" => 63, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Islampur", "state_id" => 63, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dewangonj", "state_id" => 63, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Sarishabari", "state_id" => 63, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Madarganj", "state_id" => 63, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Bokshiganj", "state_id" => 63, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Barhatta", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Durgapur", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kendua", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Atpara", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Madan", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Khaliajuri", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Kalmakanda", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Mohongonj", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Purbadhala", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Netrokona Sadar", "state_id" => 64, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Eidgaon", "state_id" => 9, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Madhyanagar", "state_id" => 39, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
            ["id" => $id++, "name" => "Dasar", "state_id" => 50, "country_id" => 1, "order" => 0, "is_default" => 0, "status" => 1],
        ];
        City::upsert($data, ['name']);
    }
}
