<?php

return [
    'name' => 'KamrulDashboard',
    'module_version' => "1.3",
    'module_type' => "plugin",
    'pid' => 92,
    'slug_pattern'   => '--slug--',
    'backup_mysql_execute_path'  => env('BACKUP_MYSQL_EXECUTE_PATH', ''),
    'driver'                     => env('SETTING_STORE_DRIVER', 'database'),
    'cache'                      => [
        'enabled' => env('CMS_SETTING_STORE_CACHE', false),
    ],
    'enable_email_smtp_settings' => env('ENABLE_EMAIL_SMTP_SETTINGS', true),
    'prefixes'  => [
//        'Modules\Post\Http\Models\Page'=>'test_Page',
//        'Modules\Post\Http\Models\Post'=>'test_Post',
//        'Modules\Post\Http\Models\Category'=>'test_Category',
    ],
    'public_single_ending_url'  => env('PUBLIC_SINGLE_ENDING_URL'),
    'admin_dir'                 => env('ADMIN_DIR', 'admin'),
    'supported' => [
        'slug' => [
            'KamrulDashboard\Post\Models\Page' => 'Pages',
        ],
    ],
    'cache_site_map'            => env('ENABLE_CACHE_SITE_MAP', false),
    'purifier'  => [
        'default' => [
            'HTML.Doctype'             => 'HTML 4.01 Transitional',
            'HTML.Allowed'             => 'div,b,strong,i,em,u,a[href|title|rel|style|target],ul,ol,li,p[style],br,span[style],img[width|height|alt|src|style],button,ins[style|data-ad-client|data-ad-slot|data-ad-format|data-full-width-responsive]',
            'HTML.AllowedElements'     => [
                'a',
                'b',
                'blockquote',
                'br',
                'code',
                'em',
                'h1',
                'h2',
                'h3',
                'h4',
                'h5',
                'h6',
                'hr',
                'i',
                'img',
                'li',
                'ol',
                'p',
                'pre',
                's',
                'span',
                'strong',
                'sub',
                'sup',
                'table',
                'tbody',
                'td',
                'th',
                'thead',
                'tr',
                'u',
                'ul',
                'pre',
                'abbr',
                'kbd',
                'var',
                'samp',
                'hr',
                'iframe',
                'figure',
                'figcaption',
                'section',
                'article',
                'aside',
                'blockquote',
                'caption',
                'del',
                'div',
                'button',
                'ins',
            ],
            'HTML.SafeIframe'          => 'true',
            // Add to .env if you want to allow all.
            // CMS_IFRAME_FILTER_URL_REGEX=/^(.*)/
            'URI.SafeIframeRegexp'     => env('IFRAME_FILTER_URL_REGEX', '%^(http://|https://|//)(' . env('IFRAME_ALLOWED_URLS', 'www.youtube.com/embed/|player.vimeo.com/video/') . ')%'),
            'Attr.AllowedFrameTargets' => ['_blank'],
            'CSS.AllowedProperties'    => [
                'font',
                'font-size',
                'font-weight',
                'font-style',
                'font-family',
                'text-decoration',
                'padding-left',
                'color',
                'background-color',
                'text-align',
                'max-width',
                'border',
                'width',
                'line-height',
                'word-spacing',
                'border-style',
                'list-style-type',
                'border-color',
                'height',
                'min-width',
                'min-height',
                'max-height',
            ],
            'CSS.MaxImgLength'         => null,
            'AutoFormat.AutoParagraph' => false,
            'AutoFormat.RemoveEmpty'   => false,
        ],
        'custom_elements'   => [
            ['u', 'Inline', 'Inline', 'Common'],
            ['button', 'Inline', 'Inline', 'Common'],
            ['ins', 'Inline', 'Inline', 'Common'],
        ],
        'custom_attributes' => [
            ['a', 'rel', 'Text'],
            ['ins', 'data-ad-client', 'Text'],
            ['ins', 'data-ad-slot', 'Text'],
            ['ins', 'data-ad-format', 'Text'],
            ['ins', 'data-ad-full-width-responsive', 'Text'],
        ],
    ],
];




